<?php
namespace Jeka\QiwiAPI\Tests\SOAP;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-17 at 15:45:45.
 */
use Jeka\QiwiAPI\SOAP\Client;

class ClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Client
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = \PHPUnit_Framework_MockObject_Generator::getMockForAbstractClass('Jeka\\QiwiAPI\\SOAP\\Client',
            array('test_login','test_password'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Jeka\QiwiAPI\SOAP\Client::setPassword
     */
    public function testSetPassword()
    {
        $this->object->setPassword('papappam');
        $this->assertEquals('papappam', $this->object->getPassword());
    }


    /**
     * @covers Jeka\QiwiAPI\SOAP\Client::getWSDLFile
     */
    public function testGetWSDLFile()
    {
        $this->assertFileExists($this->object->getWSDLFile());
    }
}
