<?php
namespace Jeka\QiwiAPI\Tests\SOAP;

use Jeka\QiwiAPI\SOAP\Service;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-17 at 11:15:45.
 */

class ServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Service
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Service;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Jeka\QiwiAPI\SOAP\Service::checkBill
     * @todo   Implement testCheckBill().
     */
    public function testCheckBill()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jeka\QiwiAPI\SOAP\Service::getBillList
     * @todo   Implement testGetBillList().
     */
    public function testGetBillList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jeka\QiwiAPI\SOAP\Service::cancelBill
     * @todo   Implement testCancelBill().
     */
    public function testCancelBill()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jeka\QiwiAPI\SOAP\Service::createBill
     * @todo   Implement testCreateBill().
     */
    public function testCreateBill()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
